---
trigger:
  - main
pool: selfHosted-sk
variables:
  imageName: thetips4you/nodeapp:latest
steps:
  - task: Docker@2
    displayName: Build an image
    inputs:
      repository: $(imageName)
      command: build
      Dockerfile: dockerfile