---
trigger:
  - main
pool: selfHosted-sk
variables:
  imageName: 'shubham1911/nodeapp'
steps:
  - task: Docker@2
    displayName: Build an image
    inputs:
      repository: $(imageName)
      command: build
      Dockerfile: dockerfile