---
trigger:
  - main
pool: selfHosted-sk
variables:
  imageName: 'shubham1911/nodeapp'
steps:
  - task: Docker@2
    displayName: Build and push an image
    inputs:
      repository: $(imageName)
      command: buildAndPush
      Dockerfile: dockerfile
      containerRegistry: dockerhub
  - task: KubernetesManifest@0
    displayName: 'Deploy to Kubernetes'
    inputs:
      action: deploy
      kubernetesServiceConnection: 'kube'
      manifests: |
        $(Pipeline.Workspace)/deploymentservice.yaml
    
    