---
apiVersion: v1
data:
  shubham2.conf: |
    ___This__is__my__configuration__file--shubham--- !!!!
kind: ConfigMap
metadata:
  name: confmap-sk-az

---
apiVersion: v1
kind: Secret
metadata:
  name: mysecret-sk-az
type: Opaque
data:
  username: c2h1YmhhbQ==
  password: c2h1YmhhbUAxMjM=

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp-deployment-sk-azure-confSec
  labels:
    app: nodeapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
      containers:
        - name: nodeserver
          image: thetips4you/nodeapp:latest
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: testconfigmap
              mountPath: /tmp/config
            - name: testsecret
              mountPath: /tmp/mysecrets
      volumes:
        - name: testconfigmap
          configMap:
            name: confmap-sk-az
            items:
              - key: shubham2.conf
                path: shubham2.conf
        - name: testsecret
          secret:
            secretName: mysecret-sk-az

---
apiVersion: v1
kind: Service
metadata:
  name: nodeapp-service-azure-sk-confsec
spec:
  selector:
    app: nodeapp
  type: NodePort
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 3000
      nodePort: 31143
