apiVersion: v1
kind: Secret
data:
  username: shubham
  password: mypassword123
metadata:
  name: testsecret
---
apiVersion: v1
data:
  shubham.conf: |
    This is my configuration file for Node_app
kind: ConfigMap
metadata:
  name: confmap-sk
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp-deployment-sk-1
  labels:
    app: nodeapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp 
    spec:
      containers:
      - name: nodeserver
        image: thetips4you/nodeapp:latest
        ports:
        - containerPort: 3000
        volumeMounts:
          - name: testconfigmap
            mountPath: "/tmp/config" 
          - name: testsecret
            mountPath: "/tmp/mysecrets"  
      volumes:
      - name: testconfigmap
        configMap:
          name: confmap-sk   
          items:
          - key: shubham.conf
            path: shubham.conf
      - name: testsecret
        secret:
          secretName: mysecret      
        
        
---

apiVersion: v1
kind: Service
metadata:
  name: nodeapp-service
spec:
  selector:
    app: nodeapp 
  type: NodePort
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 3000
    nodePort: 31111
