---
apiVersion: v1
data:
  shubham1.conf: |
    This is my configuration file !!!!
kind: ConfigMap
metadata:
  name: confmap-sk-1

---
apiVersion: v1
kind: Secret
metadata:
  name: mysecret-1
type: Opaque
data:
  username: YWRtaW4=
  password: MWYyZDFlMmU2N2Rm

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp-deployment-sk-final
  labels:
    app: nodeapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
      containers:
        - name: nodeserver
          image: thetips4you/nodeapp:latest
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: testconfigmap
              mountPath: /tmp/config
            - name: testsecret
              mountPath: /tmp/mysecrets
      volumes:
        - name: testconfigmap
          configMap:
            name: confmap-sk-1
            items:
              - key: shubham1.conf
                path: shubham1.conf
        - name: testsecret
          secret:
            secretName: mysecret-1

---
apiVersion: v1
kind: Service
metadata:
  name: nodeapp-service-final
spec:
  selector:
    app: nodeapp
  type: NodePort
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 3000
      nodePort: 31113
